---
name: tests

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: Yarn cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install npm dependencies
        run: yarn install

      - name: Run javascript tests
        run: |
          export PATH="node_modules/.bin:$PATH"
          yarn test:ci
          yarn lint
